// The Astro config the dev server loads in place of the project's own: the
// project's config wrapped with the marker integration, and the dev endpoints
// it serves to the canvas.

import { assert } from '../../shared/core/assert';

// Wraps the project's Astro config (dev preview only) with a Vite plugin
// that swaps each page's source for a marker-annotated equivalent — every
// model node sits between <!--avb-s:path--> / <!--avb-e:path--> comments so the
// preview can outline the node selected/hovered in the app. Written into
// node_modules/.avb so it never shows up in the user's git status; the file
// on disk is untouched.
// Which concrete URLs a dynamic route ([slug].astro) actually stands for.
//
// getStaticPaths is ordinary JS — it can read a content collection, hit an API,
// map over anything — so the only reliable way to know its paths is to run it,
// and the only thing that can run it is the dev server itself. Hence an
// injected endpoint rather than parsing the frontmatter.
//
// The page module is imported lazily through a glob: importing it evaluates
// module scope (where getStaticPaths lives) but not the component body, so
// nothing that needs Astro.params runs here.
export const PATHS_ENDPOINT = `// Generated by Stacki (dev preview only) — do not edit.
export const prerender = false;

const pages = import.meta.glob('/src/pages/**/*.{astro,md,mdx}');

// getStaticPaths' props ARE the page's Astro.props — the only place the editor
// can see REAL data for a dynamic route, the entry behind the canvas with its
// values in it. What crosses the wire is a SAMPLE, not the data: long strings
// are clipped, long lists cut short, deep nesting stopped, and anything JSON
// can't hold (a function, a symbol) dropped. Enough to show a designer what a
// field holds and what it is called; never enough to be worth its weight.
const MAX_STRING = 160;
const MAX_ITEMS = 8;
const MAX_DEPTH = 6;
export function sample(value, depth) {
  const d = depth || 0;
  if (value === null || value === undefined) return null;
  const t = typeof value;
  if (t === 'string') return value.length > MAX_STRING ? value.slice(0, MAX_STRING) + '…' : value;
  if (t === 'number' || t === 'boolean') return value;
  if (t !== 'object') return undefined; // functions, symbols, bigints
  // A date is a value, not a shape: kept as one, tagged so the editor can say
  // "date" rather than showing an object with no keys.
  if (value instanceof Date)
    return { __stacki: 'date', value: isNaN(value.getTime()) ? null : value.toISOString() };
  if (d >= MAX_DEPTH) return { __stacki: 'deep' };
  if (Array.isArray(value)) {
    const out = value.slice(0, MAX_ITEMS).map((v) => {
      const s = sample(v, d + 1);
      return s === undefined ? null : s;
    });
    if (value.length > MAX_ITEMS) out.push({ __stacki: 'more', count: value.length - MAX_ITEMS });
    return out;
  }
  const out = {};
  for (const key of Object.keys(value)) {
    let s;
    try {
      s = sample(value[key], d + 1);
    } catch {
      continue; // a getter that throws is not worth the whole entry
    }
    if (s !== undefined) out[key] = s;
  }
  return out;
}

// Named for the importer's sake: /__avb/data samples entries the same way.
export const SAMPLE = sample;

export async function GET({ url }) {
  const rel = url.searchParams.get('p') || '';
  const body = { entries: [], error: null };
  try {
    // The glob keys are project-root-absolute, matching what the app sends.
    const load = pages['/' + rel.replace(/^\\/+/, '')];
    if (!load) {
      body.error = 'Page not found: ' + rel;
    } else {
      const mod = await load();
      if (typeof mod.getStaticPaths === 'function') {
        const result = await mod.getStaticPaths();
        body.entries = (Array.isArray(result) ? result : [])
          .filter((e) => e && typeof e === 'object' && e.params && typeof e.params === 'object')
          .map((e, i) => ({
            params: e.params,
            // Only the first few: the editor shows ONE entry's data at a time,
            // and a collection of 400 posts would otherwise cross the wire in
            // full every time the frontmatter changes.
            props: i < 30 ? sample(e.props) : null,
          }));
      }
    }
  } catch (err) {
    body.error = String((err && err.message) || err);
  }
  return new Response(JSON.stringify(body), {
    headers: { 'content-type': 'application/json' },
  });
}
`;

// The other half of the picker's data: a page that never declares
// getStaticPaths still reads collections in its frontmatter
// (`const posts = await getCollection("blog")`), and that is the common list
// page. One entry is all a picker needs to show what a post HAS.
export const DATA_ENDPOINT = `// Generated by Stacki (dev preview only) — do not edit.
export const prerender = false;

import { SAMPLE } from './paths.js';

export async function GET({ url }) {
  const name = url.searchParams.get('c') || '';
  // A particular entry when the editor knows which one — a reference names it
  // — and otherwise the first, which is enough to show what a collection has.
  const id = url.searchParams.get('id') || '';
  const body = { entry: null, error: null };
  if (!/^[\\w-]+$/.test(name) || (id && (!/^[\\w\\-./]+$/.test(id) || id.includes('..')))) {
    body.error = 'Bad collection or entry name';
    return json(body);
  }
  try {
    // Imported here rather than at the top: a project with no content config
    // has no astro:content to import, and this route must not take the dev
    // server down with it.
    const { getCollection, getEntry } = await import('astro:content');
    if (id) {
      const entry = await getEntry(name, id);
      body.entry = entry ? SAMPLE(entry) : null;
    } else {
      const entries = await getCollection(name);
      body.entry = entries && entries.length ? SAMPLE(entries[0]) : null;
    }
  } catch (err) {
    body.error = String((err && err.message) || err);
  }
  return json(body);
}

const json = (body) =>
  new Response(JSON.stringify(body), { headers: { 'content-type': 'application/json' } });
`;

// Keep static generated source outside functions so the assembly stays reviewable.
export const MARKER_CONFIG_PARTS = [
  `// Generated by Stacki (dev preview only) — do not edit.
import { createRequire } from 'node:module';
import { readFileSync, writeFileSync } from 'node:fs';
`,
  `

const require = createRequire(import.meta.url);
// Marking happens in electron/previewServer/previewMarkers.ts, in memory: it reads project
// files and returns strings, and nothing it returns is ever written back.
const { markSourceFile, markChunkFile } = require(`,
  `);
const { componentPreviewPlugin } = require(`,
  `);
const PROJECT_DIRS = `,
  `;

// Nothing this serves is a child of anything. Every marker is a comment —
// invisible to selectors, to layout and to the box model — and the patcher
// arrives through the module graph rather than as a tag in the page. The one
// node that could hold no attribute, a <Fragment slot="…">, carries its markers
// inside itself, where they travel into the slot with its own contents.
//
// The comments stay in Stacki's #avb-design iframe. They are the one thing on the
// page that says which node is which: the patcher that replaces a full reload
// matches the server's new rendering against the live document through them, and
// without them it would be guessing from tag names. The same marked module graph
// also serves ordinary localhost tabs, so the client removes Stacki's comments and
// data attributes there after parsing and restores a normal full reload on edits.
//
// There used to be a script here that removed the <template> markers this
// served. Nothing writes one now, so there is nothing to remove — and one fewer
// tag in a page whose whole point is to be the page.

// Must hook \`load\` (not \`transform\`): Astro's own compiler plugin is also
// enforce:'pre' and runs first, so a transform would receive compiled JS —
// and returning Astro source at that point breaks the module graph.
// Astro renders components on the server, so Vite cannot hot-swap one: any
// edit to a page or a component it uses ends in "reload the document". A
// reload restarts every CSS animation, rewinds every <video>, drops scroll
// position and closes whatever the user had open — which in an editor is the
// state you were looking at when you made the change.
//
// Everything else the dev server does is wanted, including stylesheet updates
// and invalidation, so none of it is touched here. Only the one message that
// throws the page away is caught, and turned into a request to patch the page
// instead. Vite reaches the browser through more than one object and which
// one Astro picks depends on its version, so every distinct channel is
// wrapped; identity dedupes the ones that are really the same object.
// What the <style> blocks of a file said the last time it was looked at.
// Comparing the source rather than the compiled output is deliberate: Astro's
// scope hash comes from the file's path, so identical style blocks compile to
// identical CSS, and reading the file cannot disturb the module graph.
const avbStyleText = new Map();
const avbReadFile = (file) => {
  try {
    return readFileSync(file, 'utf8');
  } catch {
    return '';
  }
};
const avbStyleTextOf = (src) => (src.match(/<style[^>]*>[\\s\\S]*?<\\/style>/gi) || []).join('\\n');
const avbIsStyleModule = (m) => {
  const u = m.url || m.id || '';
  return u.indexOf('type=style') !== -1 || u.indexOf('lang.css') !== -1 || /\\.css($|\\?)/.test(u);
};

// Astro hands the browser a component's <style> from the last compile of its
// file (its load hook for \`?astro&type=style\`), and only a server-side
// transform of the file compiles it. Vite announces the new stylesheet in the
// same breath as the page change, so the browser's stylesheet request could
// reach the server before the page's render did and be answered from the
// previous edit's compile: the canvas showed every style edit one edit late.
// Astro's own style-only path compiles first, but it compares the file on disk
// with the marked copy served below, whose stamp carries the file's checksum,
// so it never fires here. A real change to a file's <style> blocks is
// therefore compiled server side before the browser hears of it. Vite has
// invalidated the file by then and awaits this hook before it sends anything
// (Vite 6 and 8 alike). A transform that fails or runs long leaves Vite's own
// order, as before.
const AVB_RECOMPILE_MS_MAX = 3000;
const AVB_RECOMPILES_MAX = 256;
const avbRecompiles = new Map(); // file -> its compile in flight; two edits compile in order
// The first server environment whose graph holds the file, ssr first: Astro's
// compile cache is shared by every environment, so one compile serves all.
// None on Vite 5 (no environments) or for a file nothing has rendered yet.
const avbServerTransform = (server, file) => {
  const environments = (server && server.environments) || {};
  const names = ['ssr', ...Object.keys(environments).filter((name) => name !== 'ssr')];
  for (const name of names) {
    const environment = environments[name];
    if (!environment || !environment.config || environment.config.consumer !== 'server') continue;
    if (typeof environment.transformRequest !== 'function' || !environment.moduleGraph) continue;
    for (const m of environment.moduleGraph.getModulesByFile(file) || []) {
      if (m.url && m.id && m.id.indexOf('?') === -1) {
        return () => environment.transformRequest(m.url);
      }
    }
  }
  return undefined;
};
// Resolves true once the file is compiled, or when there is nothing to
// compile; false when the compile failed or outran AVB_RECOMPILE_MS_MAX. The
// next edit's compile waits for this one's answer, not for its transform: a
// transform that never settles holds up one edit by the bound, not every
// edit after it.
const avbRecompile = (server, file) => {
  const transform = avbServerTransform(server, file);
  if (!transform) return Promise.resolve(true);
  const previous = avbRecompiles.get(file) || Promise.resolve(true);
  let timer;
  const late = new Promise((resolve) => {
    timer = setTimeout(() => resolve(false), AVB_RECOMPILE_MS_MAX);
  });
  const compiled = previous.then(transform).then(() => true, () => false);
  const answered = Promise.race([compiled, late]).finally(() => clearTimeout(timer));
  if (avbRecompiles.has(file) || avbRecompiles.size < AVB_RECOMPILES_MAX) {
    avbRecompiles.set(file, answered);
    answered.then(() => {
      if (avbRecompiles.get(file) === answered) avbRecompiles.delete(file);
    });
  }
  return answered;
};

const avbMorph = {
  name: 'avb-morph',
  resolveId(id) {
    if (id === 'virtual:avb-morph') return '\0virtual:avb-morph';
    return null;
  },
  load(id) {
    return id === '\0virtual:avb-morph' ? `,
  ` : null;
  },
  // Vite reapplies a page's extracted stylesheet whenever its .astro file
  // changes, whether or not a single character of that CSS is different. The
  // browser treats the rewritten <style> as a new stylesheet, so every
  // animation it defines starts over — once per keystroke while typing into a
  // text field, which is exactly the thing this feature exists to stop. When
  // the style blocks in the file are byte for byte what they were, the
  // stylesheet updates are dropped and only the page patch goes out. A real
  // CSS edit compares differently: it is compiled first (avbRecompile), then
  // takes Vite's own path. A compile that is not confirmed is not trusted:
  // the file's entry is forgotten, so the next update passes and compiles too.
  async handleHotUpdate(ctx) {
    if (!/\\.(astro|md|mdx)$/i.test(ctx.file)) return;
    const before = avbStyleText.get(ctx.file);
    const now = avbStyleTextOf(avbReadFile(ctx.file));
    avbStyleText.set(ctx.file, now);
    if (before === undefined || before !== now) {
      // Only an .astro file has \`?astro&type=style\` modules to refresh.
      if (/\\.astro$/i.test(ctx.file) && !(await avbRecompile(ctx.server, ctx.file))) {
        avbStyleText.delete(ctx.file);
      }
      return;
    }
    const rest = ctx.modules.filter((m) => !avbIsStyleModule(m));
    return rest.length === ctx.modules.length ? undefined : rest;
  },
  configureServer(server) {
    const seen = new Set();
    const channels = [server.hot, server.ws];
    for (const env of Object.values(server.environments || {})) channels.push(env && env.hot);
    for (const ch of channels) {
      if (!ch || typeof ch.send !== 'function' || seen.has(ch)) continue;
      seen.add(ch);
      const send = ch.send.bind(ch);
      ch.send = (...args) => {
        const payload = args[0];
        if (payload && payload.type === 'full-reload') {
          return send({ type: 'custom', event: 'avb:page-changed' });
        }
        return send(...args);
      };
    }
  },
};

const AVB_MORPH_TAG = `,
  `;

const avbMarkers = {
  name: 'avb-node-markers',
  enforce: 'pre',
  load(id) {
    const qi = id.indexOf('?');
    const file = qi === -1 ? id : id.slice(0, qi);
    const query = qi === -1 ? '' : id.slice(qi + 1);
    // A <Fragment set:html={x} /> renders from an imported HTML string, so
    // the page's own markers can't reach inside it. serializePageMarked tags
    // the ?raw import with the Fragment's key; mark the chunk here so its
    // nodes outline like any other. Runs before vite:asset's own ?raw load.
    if (query) {
      const m = /(?:^|&)avb=([^&]+)/.exec(query);
      if (!m) return null;
      try {
        const marked = markChunkFile(file, decodeURIComponent(m[1]), {
          group: /(?:^|&)avbg=1(?:&|$)/.test(query),
        });
        return marked == null ? null : 'export default ' + JSON.stringify(marked) + ';';
      } catch {
        return null;
      }
    }
    // Pages mark with bare paths, every other .astro under src with its own
    // namespace, and each marked file carries its stamp — the checksum of the
    // bytes it was marked from, which the canvas's preview token is made of.
    try {
      const marked = markSourceFile(file, PROJECT_DIRS);
      if (!marked) return null;
      // Seeded here so the very first edit already has something to compare
      // against, rather than spending one stylesheet rewrite learning it.
      if (!avbStyleText.has(file)) avbStyleText.set(file, avbStyleTextOf(marked.source));
      // The patcher rides along with a page — Astro hoists it into <head>,
      // so this adds a module to the page and no node to its markup.
      return marked.page ? marked.code + AVB_MORPH_TAG : marked.code;
    } catch {
      return null;
    }
  },
};

// Markdown can't use the load hook above: Astro's own \`astro:markdown\` plugin
// is enforce:'pre', owns load for .md, and reads the file off disk itself — so
// there is nothing to intercept. The document AST is the hook it does hand out,
// and it's the right place anyway.
//
// One marker pair per ROOT node, numbered to match that block's index in the
// app's tree. Frontmatter isn't in the tree so it isn't counted; an MDX import
// is (the app keeps it as a node) but isn't wrapped, because a template in the
// middle of the import block would be rendered content.
const AVB_BLOCK_TYPES = [
  'paragraph', 'heading', 'thematicBreak', 'blockquote', 'list', 'html', 'code',
  'definition', 'footnoteDefinition', 'table', 'math', 'containerDirective',
  'leafDirective', 'mdxJsxFlowElement', 'mdxFlowExpression',
];
const avbSatteriMarkers = () => {
  const plugin = { name: 'avb-node-markers' };
  const visit = (node, ctx) => {
    const parent = ctx.parent(node);
    if (!parent || parent.type !== 'root') return;
    const raw = ctx.indexOf(node);
    if (raw == null) return;
    // Frontmatter is a root child here but not a node in the app's tree, so
    // everything after it would be numbered one too high.
    const children = parent.children || [];
    let offset = 0;
    for (let i = 0; i < raw && i < children.length; i++) {
      if (children[i] && (children[i].type === 'yaml' || children[i].type === 'toml')) offset++;
    }
    const path = String(raw - offset);
    ctx.insertBefore(node, { type: 'html', value: '<!--avb-s:' + path + '-->' });
    ctx.insertAfter(node, { type: 'html', value: '<!--avb-e:' + path + '-->' });
  };
  for (const type of AVB_BLOCK_TYPES) plugin[type] = visit;
  return plugin;
};

// Only when the project is on the processor Astro ships by default, and only
// when it hasn't chosen its own. \`markdown.remarkPlugins\` is NOT a safe
// fallback: on Astro 7 it needs @astrojs/markdown-remark installed, and setting
// it without that fails config validation — the dev server wouldn't start at
// all. A project this can't reach simply gets no markdown outlines; editing
// through the navigator is unaffected.
let avbMarkdownProcessor = null;
try {
  const { satteri } = await import('@astrojs/markdown-satteri');
  avbMarkdownProcessor = satteri({ mdastPlugins: [avbSatteriMarkers] });
} catch {
  /* different Astro, different processor — skip the markers */
}

// Isolated component previews for the palette hover cards.
const avbPreviewRoute = {
  name: 'avb-preview-route',
  hooks: {
    // The app builds canvas URLs from page file paths, and \`trailingSlash\`
    // decides whether this server answers /de/hotel or /de/hotel/. Hand back
    // the resolved value — it has been through Astro's defaults, and it holds
    // however the project arrived at it, literal or not.
    'astro:config:done': ({ config }) => {
      try {
        writeFileSync(
          new URL('./resolved.json', import.meta.url),
          JSON.stringify({ trailingSlash: config.trailingSlash, base: config.base })
        );
      } catch {
        /* the app falls back to reading the config's text */
      }
    },
    // Every route this project will serve, as Astro resolved it — the files
    // under src/pages AND anything an integration injected. A site whose pages
    // come from a package has nothing on disk for the app to find (issue #7),
    // and this list is the only place they exist. Written beside resolved.json
    // rather than served: the app already reads that directory, and a file
    // needs no route of its own to fetch it through.
    'astro:routes:resolved': ({ routes }) => {
      try {
        writeFileSync(
          new URL('./routes.json', import.meta.url),
          JSON.stringify(
            (routes || [])
              .filter((r) => r && r.pattern && !String(r.pattern).startsWith('/__avb'))
              .map((r) => ({
                pattern: r.pattern,
                // 'project' is a file under src/pages, 'external' came from an
                // integration, 'internal' is Astro's own (404, and friends).
                origin: r.origin || null,
                entrypoint: r.entrypoint || null,
                params: r.params || [],
              }))
          )
        );
      } catch {
        /* an Astro without this hook simply never calls it */
      }
    },
    'astro:config:setup': ({ injectRoute }) => {
      injectRoute({ pattern: '/__avb/preview', entrypoint: `,
  ` });
      injectRoute({ pattern: '/__avb/paths', entrypoint: `,
  ` });
      injectRoute({ pattern: '/__avb/data', entrypoint: `,
  ` });
    },
  },
};

const base = userConfig || {};
export default {
  ...base,
  // The floating dev toolbar is viewport-fixed clutter in an editor canvas,
  // and it would sit on top of component thumbnails. Only this app's dev
  // server is affected — the project's own \`astro dev\` is untouched.
  devToolbar: { enabled: false },
  // Astro compresses HTML by default, and the marker <template>s above turn a
  // text node's boundary whitespace into whitespace between elements — which
  // the compressor is free to drop. "Be <Rotator />" then renders as
  // "BeFOUND." on the canvas while the real build keeps the space. Off here
  // so the canvas shows the spacing the source actually has; the project's
  // own dev server and build keep whatever it configured.
  compressHTML: false,
  integrations: [...(base.integrations || []), avbPreviewRoute],
  markdown: {
    ...(base.markdown || {}),
    ...(avbMarkdownProcessor && !(base.markdown && base.markdown.processor)
      ? { processor: avbMarkdownProcessor }
      : {}),
  },
  vite: {
    ...(base.vite || {}),
    plugins: [componentPreviewPlugin(PROJECT_DIRS), avbMarkers, avbMorph,
      ...((base.vite && base.vite.plugins) || [])],
  },
};
`,
] as const;

export function renderMarkerConfig(values: readonly string[]): string {
  assert(values.length + 1 === MARKER_CONFIG_PARTS.length, 'Marker template interpolation count');
  const source = MARKER_CONFIG_PARTS.map((part, index) => part + (values[index] ?? '')).join('');
  assert(source.startsWith('// Generated by Stacki'), 'Marker config must retain its header');
  return source;
}
